services:
  - type: web
    name: halaltube-backend-proxy
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
