import { importProvidersFrom } from '@angular/core';
import { 
  LucideAngularModule, LayoutDashboard, MessageCircleQuestion, Gamepad2, Clock, HeartPulse, 
  MessageSquare, Cpu, HardDrive, Table, Tag, MessageCircle, Video, ShoppingCart, 
  GraduationCap, LibraryBig, Megaphone, DownloadCloud, Rocket, Wallet, Repeat, 
  CircuitBoard, Library, Microscope, Users, BookOpen, Zap, Bell, Settings, ShieldCheck, 
  LogOut, X, GripVertical, Pin, PinOff, Menu, SlidersHorizontal, Minimize2, 
  LayoutPanelLeft, ChevronUp, ChevronDown, Layers, Home, Film, History, Tv, 
  TrendingUp, Music, Newspaper, Search, Sparkles, ArrowLeft, ArrowUp, ArrowDown, ArrowRight, Move, ThumbsUp, Play,
  ExternalLink, Settings2, Palette, PlusCircle, Download, Activity, Box,
  PanelLeft, PanelRight, PanelTop, PanelBottom, Orbit, MoreVertical, ChevronLeft, ChevronRight,
  Flame, Plus, ShoppingBag, Receipt, Minus, Trash2, Loader2, Croissant, Coffee,
  Monitor, Edit, CheckCircle2, CheckSquare, Check, UploadCloud, FileText,
  Terminal, Code2, Server, Key, Wifi, WifiOff, Unlink, AlertCircle, AlertTriangle, RefreshCw,
  Globe, Link, BookmarkPlus, Github, Wrench, UserCog, MapPin, Truck, Copy, Filter, FileDown, Calculator,
  Map, PackageOpen, Heart, Warehouse, Eye, Printer, HelpCircle, Info, CreditCard, ShieldAlert,
  UserCheck, BellRing, Tags, Edit3, Ban, User, Phone, Package, CheckCircle, BellOff,
  PackagePlus, Camera, PenTool, Grid, Maximize2, Pause, VolumeX, Volume2, LoaderCircle,
  Maximize, Star, Timer, Sun, Moon, Chrome, CloudCog, CloudUpload, CloudRain, Flag, Lock, BarChart3,
  Type, Code, Bookmark, Building2, Smartphone, Workflow, Database,
  ScanText, Crop, RotateCw, RotateCcw, ZoomIn, ZoomOut, FileSearch, Sliders, Languages, Share2, FileArchive
} from 'lucide-angular';

import { 
  provideLucideIcons as provideNewLucideIcons,
  LucideFileArchive,
  LucideBuilding2,
  LucideSmartphone,
  LucideWorkflow,
  LucideDatabase,
  LucideScanText,
  LucideCrop,
  LucideRotateCw,
  LucideRotateCcw,
  LucideZoomIn,
  LucideZoomOut,
  LucideFileSearch,
  LucideSliders,
  LucideLanguages,
  LucideShare2,
  LucideLayoutDashboard, LucideMessageCircleQuestion, LucideGamepad2, LucideClock, LucideHeartPulse, 
  LucideMessageSquare, LucideCpu, LucideHardDrive, LucideTable, LucideTag, LucideMessageCircle, LucideVideo, LucideShoppingCart, 
  LucideGraduationCap, LucideLibraryBig, LucideMegaphone, LucideDownloadCloud, LucideRocket, LucideWallet, LucideRepeat, 
  LucideCircuitBoard, LucideLibrary, LucideMicroscope, LucideUsers, LucideBookOpen, LucideZap, LucideBell, LucideSettings, LucideShieldCheck, 
  LucideLogOut, LucideX, LucideGripVertical, LucidePin, LucidePinOff, LucideMenu, LucideSlidersHorizontal, LucideMinimize2, 
  LucideLayoutPanelLeft, LucideChevronUp, LucideChevronDown, LucideLayers, LucideHome, LucideFilm, LucideHistory, LucideTv, 
  LucideTrendingUp, LucideMusic, LucideNewspaper, LucideSearch, LucideSparkles, LucideArrowLeft, LucideArrowUp, LucideArrowDown, LucideArrowRight, LucideMove, LucideThumbsUp, LucidePlay,
  LucideExternalLink, LucideSettings2, LucidePalette, LucidePlusCircle, LucideDownload, LucideActivity, LucideBox,
  LucidePanelLeft, LucidePanelRight, LucidePanelTop, LucidePanelBottom, LucideOrbit, LucideMoreVertical, LucideChevronLeft, LucideChevronRight,
  LucideFlame, LucidePlus, LucideShoppingBag, LucideReceipt, LucideMinus, LucideTrash2, LucideLoader2, LucideCroissant, LucideCoffee,
  LucideMonitor, LucideEdit, LucideCheckCircle2, LucideCheckSquare, LucideCheck, LucideUploadCloud, LucideFileText,
  LucideTerminal, LucideCode2, LucideServer, LucideKey, LucideWifi, LucideWifiOff, LucideUnlink, LucideAlertCircle, LucideAlertTriangle, LucideRefreshCw,
  LucideGlobe, LucideLink, LucideBookmarkPlus, LucideWrench, LucideUserCog, LucideMapPin, LucideTruck, LucideCopy, LucideFilter, LucideFileDown, LucideCalculator,
  LucideMap, LucidePackageOpen, LucideHeart, LucideWarehouse, LucideEye, LucidePrinter, LucideHelpCircle, LucideInfo, LucideCreditCard, LucideShieldAlert,
  LucideUserCheck, LucideBellRing, LucideTags, LucideEdit3, LucideBan, LucideUser, LucidePhone, LucidePackage, LucideCheckCircle, LucideBellOff,
  LucidePackagePlus, LucideCamera, LucidePenTool, LucideGrid, LucideMaximize2, LucidePause, LucideVolumeX, LucideVolume2, LucideLoaderCircle,
  LucideMaximize, LucideStar, LucideTimer, LucideSun, LucideMoon, LucideCloudCog, LucideCloudUpload, LucideCloudRain, LucideFlag, LucideLock, LucideBarChart3
} from '@lucide/angular';

export const provideLucideIcons = () => {
  return [
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        MessageCircleQuestion,
        Gamepad2,
        Clock,
        HeartPulse,
        MessageSquare,
        Cpu,
        HardDrive,
        Table,
        Tag,
        MessageCircle,
        Video,
        ShoppingCart,
        GraduationCap,
        LibraryBig,
        Megaphone,
        DownloadCloud,
        Rocket,
        Wallet,
        Repeat,
        CircuitBoard,
        Library,
        Microscope,
        Users,
        BookOpen,
        Zap,
        Bell,
        Settings,
        ShieldCheck,
        LogOut,
        X,
        GripVertical,
        Pin,
        PinOff,
        Menu,
        SlidersHorizontal,
        Minimize2,
        LayoutPanelLeft,
        ChevronUp,
        ChevronDown,
        Layers,
        Home,
        Film,
        History,
        Tv,
        TrendingUp,
        Music,
        Newspaper,
        Search,
        Sparkles,
        ArrowLeft,
        ArrowUp,
        ArrowDown,
        ArrowRight,
        Move,
        ThumbsUp,
        Play,
        ExternalLink,
        Settings2,
        Palette,
        PlusCircle,
        Download,
        Activity,
        Box,
        PanelLeft,
        PanelRight,
        PanelTop,
        PanelBottom,
        Orbit,
        MoreVertical,
        ChevronLeft,
        ChevronRight,
        Flame,
        Plus,
        ShoppingBag,
        Receipt,
        Minus,
        Trash2,
        Loader2,
        Croissant,
        Coffee,
        Monitor,
        Edit,
        CheckCircle2,
        CheckSquare,
        Check,
        UploadCloud,
        FileText,
        Terminal,
        Code2,
        Server,
        Key,
        Wifi,
        WifiOff,
        Unlink,
        AlertCircle,
        AlertTriangle,
        RefreshCw,
        Globe,
        Link,
        BookmarkPlus,
        Github,
        Wrench,
        UserCog,
        MapPin,
        Truck,
        Copy,
        Filter,
        FileDown,
        Calculator,
        Map,
        PackageOpen,
        Heart,
        Warehouse,
        Eye,
        Printer,
        HelpCircle,
        Info,
        CreditCard,
        ShieldAlert,
        UserCheck,
        BellRing,
        Tags,
        Edit3,
        Ban,
        User,
        Phone,
        Package,
        CheckCircle,
        BellOff,
        PackagePlus,
        Camera,
        PenTool,
        Grid,
        Maximize2,
        Pause,
        VolumeX,
        Volume2,
        LoaderCircle,
        Maximize,
        Star,
        Timer,
        Sun,
        Moon,
        Chrome,
        CloudCog,
        CloudUpload,
        CloudRain,
        Flag,
        Lock,
        BarChart3,
        Type,
        Code,
        Bookmark,
        Building2,
        Smartphone,
        Workflow,
        Database,
        ScanText,
        Crop,
        RotateCw,
        RotateCcw,
        ZoomIn,
        ZoomOut,
        FileSearch,
        Sliders,
        Languages,
        Share2,
        FileArchive
      })
    ),
    provideNewLucideIcons(
      LucideFileArchive,
      LucideBuilding2,
      LucideLayoutDashboard,
      LucideMessageCircleQuestion,
      LucideGamepad2,
      LucideClock,
      LucideHeartPulse,
      LucideMessageSquare,
      LucideCpu,
      LucideHardDrive,
      LucideTable,
      LucideTag,
      LucideMessageCircle,
      LucideVideo,
      LucideShoppingCart,
      LucideGraduationCap,
      LucideLibraryBig,
      LucideMegaphone,
      LucideDownloadCloud,
      LucideRocket,
      LucideWallet,
      LucideRepeat,
      LucideCircuitBoard,
      LucideLibrary,
      LucideMicroscope,
      LucideUsers,
      LucideBookOpen,
      LucideZap,
      LucideBell,
      LucideSettings,
      LucideShieldCheck,
      LucideLogOut,
      LucideX,
      LucideGripVertical,
      LucidePin,
      LucidePinOff,
      LucideMenu,
      LucideSlidersHorizontal,
      LucideMinimize2,
      LucideLayoutPanelLeft,
      LucideChevronUp,
      LucideChevronDown,
      LucideLayers,
      LucideHome,
      LucideFilm,
      LucideHistory,
      LucideTv,
      LucideTrendingUp,
      LucideMusic,
      LucideNewspaper,
      LucideSearch,
      LucideSparkles,
      LucideArrowLeft,
      LucideArrowUp,
      LucideArrowDown,
      LucideArrowRight,
      LucideMove,
      LucideThumbsUp,
      LucidePlay,
      LucideExternalLink,
      LucideSettings2,
      LucidePalette,
      LucidePlusCircle,
      LucideDownload,
      LucideActivity,
      LucideBox,
      LucidePanelLeft,
      LucidePanelRight,
      LucidePanelTop,
      LucidePanelBottom,
      LucideOrbit,
      LucideMoreVertical,
      LucideChevronLeft,
      LucideChevronRight,
      LucideFlame,
      LucidePlus,
      LucideShoppingBag,
      LucideReceipt,
      LucideMinus,
      LucideTrash2,
      LucideLoader2,
      LucideCroissant,
      LucideCoffee,
      LucideMonitor,
      LucideEdit,
      LucideCheckCircle2,
      LucideCheckSquare,
      LucideCheck,
      LucideUploadCloud,
      LucideFileText,
      LucideTerminal,
      LucideCode2,
      LucideServer,
      LucideKey,
      LucideWifi,
      LucideWifiOff,
      LucideUnlink,
      LucideAlertCircle,
      LucideAlertTriangle,
      LucideRefreshCw,
      LucideGlobe,
      LucideLink,
      LucideBookmarkPlus,
      LucideWrench,
      LucideUserCog,
      LucideMapPin,
      LucideTruck,
      LucideCopy,
      LucideFilter,
      LucideFileDown,
      LucideCalculator,
      LucideMap,
      LucidePackageOpen,
      LucideHeart,
      LucideWarehouse,
      LucideEye,
      LucidePrinter,
      LucideHelpCircle,
      LucideInfo,
      LucideCreditCard,
      LucideShieldAlert,
      LucideUserCheck,
      LucideBellRing,
      LucideTags,
      LucideEdit3,
      LucideBan,
      LucideUser,
      LucidePhone,
      LucidePackage,
      LucideCheckCircle,
      LucideBellOff,
      LucidePackagePlus,
      LucideCamera,
      LucidePenTool,
      LucideGrid,
      LucideMaximize2,
      LucidePause,
      LucideVolumeX,
      LucideVolume2,
      LucideLoaderCircle,
      LucideMaximize,
      LucideStar,
      LucideTimer,
      LucideSun,
      LucideMoon,
      LucideCloudCog,
      LucideCloudUpload,
      LucideCloudRain,
      LucideFlag,
      LucideLock,
      LucideBarChart3,
      LucideSmartphone,
      LucideWorkflow,
      LucideDatabase,
      LucideScanText,
      LucideCrop,
      LucideRotateCw,
      LucideRotateCcw,
      LucideZoomIn,
      LucideZoomOut,
      LucideFileSearch,
      LucideSliders,
      LucideLanguages,
      LucideShare2
    )
  ];
};
