import { importProvidersFrom } from '@angular/core';
import { 
  LucideAngularModule, LayoutDashboard, MessageCircleQuestion, Gamepad2, Clock, HeartPulse, 
  MessageSquare, Cpu, HardDrive, Table, Tag, MessageCircle, Video, ShoppingCart, 
  GraduationCap, LibraryBig, Megaphone, DownloadCloud, Rocket, Wallet, Repeat, 
  CircuitBoard, Library, Microscope, Users, BookOpen, Zap, Bell, Settings, ShieldCheck, 
  LogOut, X, GripVertical, Pin, PinOff, Menu, SlidersHorizontal, Minimize2, 
  LayoutPanelLeft, ChevronUp, ChevronDown, Layers, Home, Film, History, Tv, 
  TrendingUp, Music, Newspaper, Search, Sparkles, ArrowLeft, ThumbsUp, Play,
  ExternalLink, Settings2, Palette, PlusCircle, Download, Activity, Box,
  PanelLeft, PanelRight, PanelTop, PanelBottom, Orbit, MoreVertical, ChevronLeft
} from 'lucide-angular';

import { 
  provideLucideIcons as provideNewLucideIcons,
  LucideLayoutDashboard, LucideMessageCircleQuestion, LucideGamepad2, LucideClock, LucideHeartPulse, 
  LucideMessageSquare, LucideCpu, LucideHardDrive, LucideTable, LucideTag, LucideMessageCircle, LucideVideo, LucideShoppingCart, 
  LucideGraduationCap, LucideLibraryBig, LucideMegaphone, LucideDownloadCloud, LucideRocket, LucideWallet, LucideRepeat, 
  LucideCircuitBoard, LucideLibrary, LucideMicroscope, LucideUsers, LucideBookOpen, LucideZap, LucideBell, LucideSettings, LucideShieldCheck, 
  LucideLogOut, LucideX, LucideGripVertical, LucidePin, LucidePinOff, LucideMenu, LucideSlidersHorizontal, LucideMinimize2, 
  LucideLayoutPanelLeft, LucideChevronUp, LucideChevronDown, LucideLayers, LucideHome, LucideFilm, LucideHistory, LucideTv, 
  LucideTrendingUp, LucideMusic, LucideNewspaper, LucideSearch, LucideSparkles, LucideArrowLeft, LucideThumbsUp, LucidePlay,
  LucideExternalLink, LucideSettings2, LucidePalette, LucidePlusCircle, LucideDownload, LucideActivity, LucideBox,
  LucidePanelLeft, LucidePanelRight, LucidePanelTop, LucidePanelBottom, LucideOrbit, LucideMoreVertical, LucideChevronLeft
} from '@lucide/angular';

export const provideLucideIcons = () => {
  return [
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        MessageCircleQuestion,
        Gamepad2,
        Clock,
        HeartPulse,
        MessageSquare,
        Cpu,
        HardDrive,
        Table,
        Tag,
        MessageCircle,
        Video,
        ShoppingCart,
        GraduationCap,
        LibraryBig,
        Megaphone,
        DownloadCloud,
        Rocket,
        Wallet,
        Repeat,
        CircuitBoard,
        Library,
        Microscope,
        Users,
        BookOpen,
        Zap,
        Bell,
        Settings,
        ShieldCheck,
        LogOut,
        X,
        GripVertical,
        Pin,
        PinOff,
        Menu,
        SlidersHorizontal,
        Minimize2,
        LayoutPanelLeft,
        ChevronUp,
        ChevronDown,
        Layers,
        Home,
        Film,
        History,
        Tv,
        TrendingUp,
        Music,
        Newspaper,
        Search,
        Sparkles,
        ArrowLeft,
        ThumbsUp,
        Play,
        ExternalLink,
        Settings2,
        Palette,
        PlusCircle,
        Download,
        Activity,
        Box,
        PanelLeft,
        PanelRight,
        PanelTop,
        PanelBottom,
        Orbit,
        MoreVertical,
        ChevronLeft
      })
    ),
    provideNewLucideIcons(
      LucideLayoutDashboard,
      LucideMessageCircleQuestion,
      LucideGamepad2,
      LucideClock,
      LucideHeartPulse,
      LucideMessageSquare,
      LucideCpu,
      LucideHardDrive,
      LucideTable,
      LucideTag,
      LucideMessageCircle,
      LucideVideo,
      LucideShoppingCart,
      LucideGraduationCap,
      LucideLibraryBig,
      LucideMegaphone,
      LucideDownloadCloud,
      LucideRocket,
      LucideWallet,
      LucideRepeat,
      LucideCircuitBoard,
      LucideLibrary,
      LucideMicroscope,
      LucideUsers,
      LucideBookOpen,
      LucideZap,
      LucideBell,
      LucideSettings,
      LucideShieldCheck,
      LucideLogOut,
      LucideX,
      LucideGripVertical,
      LucidePin,
      LucidePinOff,
      LucideMenu,
      LucideSlidersHorizontal,
      LucideMinimize2,
      LucideLayoutPanelLeft,
      LucideChevronUp,
      LucideChevronDown,
      LucideLayers,
      LucideHome,
      LucideFilm,
      LucideHistory,
      LucideTv,
      LucideTrendingUp,
      LucideMusic,
      LucideNewspaper,
      LucideSearch,
      LucideSparkles,
      LucideArrowLeft,
      LucideThumbsUp,
      LucidePlay,
      LucideExternalLink,
      LucideSettings2,
      LucidePalette,
      LucidePlusCircle,
      LucideDownload,
      LucideActivity,
      LucideBox,
      LucidePanelLeft,
      LucidePanelRight,
      LucidePanelTop,
      LucidePanelBottom,
      LucideOrbit,
      LucideMoreVertical,
      LucideChevronLeft
    )
  ];
};
